"""Mathematical problems independent of meshes and material instances."""

from .elasticity import (
    BearingDevice2d,
    CantileverCorner2d,
    CantileverMiddle2d,
    CantileverRightBottomEdge3d,
    DivergenceFreePolynomialElasticity3D,
    ExponentialSineManufacturedElasticity2D,
    FullMBBBeam2d,
    FullMBBBeam3d,
    FixedFixedBeamCenterLoad2d,
    FixedFixedBeamHalfDomain2d,
    HalfMBBBeamRight2d,
    HalfMBBBeamRight3d,
    HarmonicPoly2D,
    HarmonicPoly3D,
    HarmonicPolynomialElasticity2D,
    HarmonicPolynomialElasticity3D,
    MixedBoundaryExponentialSineElasticity2D,
    MixedBoundarySinusoidalElasticity2D,
    SimplySupportedBridge2d,
    SinusoidalElasticity2D,
    SinusoidalPlaneStrainElasticity2D,
)
from .loads import (
    BodyForceLoad,
    BoundaryTractionLoad,
    LineTractionLoad,
    PointForceLoad,
)

__all__ = [
    "BearingDevice2d",
    "BodyForceLoad",
    "BoundaryTractionLoad",
    "CantileverCorner2d",
    "CantileverMiddle2d",
    "CantileverRightBottomEdge3d",
    "DivergenceFreePolynomialElasticity3D",
    "ExponentialSineManufacturedElasticity2D",
    "FullMBBBeam2d",
    "FullMBBBeam3d",
    "FixedFixedBeamCenterLoad2d",
    "FixedFixedBeamHalfDomain2d",
    "HalfMBBBeamRight2d",
    "HalfMBBBeamRight3d",
    "HarmonicPoly2D",
    "HarmonicPoly3D",
    "HarmonicPolynomialElasticity2D",
    "HarmonicPolynomialElasticity3D",
    "LineTractionLoad",
    "MixedBoundaryExponentialSineElasticity2D",
    "MixedBoundarySinusoidalElasticity2D",
    "PointForceLoad",
    "SimplySupportedBridge2d",
    "SinusoidalElasticity2D",
    "SinusoidalPlaneStrainElasticity2D",
]
